R = None
pipeline = None
data_mem = []
unit_statuses = []
stages = []
instr_exec = 0
debug_timing = True
issue_rate = 2
ROB = None
ROB_entries = 20
# retire_rate = issue_rate + 2
retire_rate = issue_rate
bypassing = True
speculating = False
speculationEnabled = True
debug_spec = True
