R = None
pipeline = None
data_mem = []
unit_statuses = []
enable_forwarding = True
# enable_forwarding = False
is_pipelined = False
stages = []
is_simpy = False
instr_exec = 0
debug_timing = False
ROB_entries = 16
retire_rate = 1
ROB = None
