write(true | false);
writeln;
write(false | true);
writeln;
write(!(false | (true & !false)));
writeln;
write(!(!(false | (true & !false))));
writeln;
write(true & !(false | (true | (true & !true))));
writeln;
